version: '3'

networks:
  nrgyinvoicr_network:

services:

  postgres:
    container_name: postgres
    image: bkaminnski/postgres-initializable
    environment:
    - POSTGRES_PASSWORD=postgres
    # Databases to initialize separated by space. For each database "db user"="db name"="SERVICE_NAME". Format: SERVICE1_NAME;DB1_PASSWORD SERVICE2_NAME;DB2_PASSWORD ...
    - INITIAL_DATABASES=nrgyinvoicr;nrgyinvoicr
    ports:
    - "5432:5432"
    expose:
    - "5432"
    command: postgres
    networks:
    - nrgyinvoicr_network
