spring:
  application:
    name: nrgyinvoicr
  datasource:
    url: jdbc:postgresql://localhost:5432/nrgyinvoicr
    username: nrgyinvoicr
    password: nrgyinvoicr
  jpa:
    generate-ddl: false
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

server:
  port: 8080
