spring:
  application:
    name: nrgyinvoicr
  servlet:
    multipart:
      max-file-size: 170MB
      max-request-size: 170MB
  datasource:
    url: jdbc:postgresql://localhost:5432/nrgyinvoicr
    username: nrgyinvoicr
    password: nrgyinvoicr
  jpa:
    generate-ddl: false
    properties:
      hibernate:
        jdbc:
          batch_size: 500
        order_inserts: true
        order_updates: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

server:
  port: 8080

nrgyinvoicr:
  timezone: Europe/Berlin
  invoiceNumberTemplate: ENR/%06d
  vat: 0.23
  invoiceFolder: /tmp/